#pragma once
#ifndef CHATROOM_TYPE_H
#define CHATROOM_TYPE_H
enum CHATROOM_TYPE
{
	CHATROOM_TYPE_UNABLE,	// 占位
	CHATROOM_TYPE_PUBLIC,	// 无需登录和验证
	CHATROOM_TYPE_LOGIN		// 需要登录，无需验证
};

enum CHATROOM_LIST_TYPE
{
	CHATROOM_LIST_TYPE_CHATROOM,
	CHATROOM_LIST_TYPE_LIVE,
	CHATROOM_LIST_TYPE_LIVE_PUSH,
	CHATROOM_LIST_TYPE_MEETING,
	CHATROOM_LIST_TYPE_MEETING_PUSH,
	CHATROOM_LIST_TYPE_CLASS,
	CHATROOM_LIST_TYPE_CLASS_PUSH
};
#endif