#pragma once
#ifndef CHATROOM_TYPE_H
#define CHATROOM_TYPE_H
enum XH_CHATROOM_TYPE
{
	XH_CHATROOM_TYPE_UNABLE,		// 占位
	XH_CHATROOM_TYPE_GLOBAL_PUBLIC,	// 无需登录和验证
	XH_CHATROOM_TYPE_LOGIN_PUBLIC	// 需要登录，无需验证
};

/**
   * 直播类型
   */
enum XH_LIVE_TYPE
{
	XH_LIVE_TYPE_GLOBAL_PUBLIC, //无需登录和验证
	XH_LIVE_TYPE_LOGIN_PUBLIC, //需要登录，无需验证
	XH_LIVE_TYPE_LOGIN_SPECIFY //需要登录和验证
};

/**
 * 会议类型
 */
enum XH_MEETING_TYPE
{
	XH_MEETING_TYPE_GLOBAL_PUBLIC, //无需登录和验证
	XH_MEETING_TYPE_LOGIN_PUBLIC, //需要登录，无需验证
	XH_MEETING_TYPE_LOGIN_SPECIFY //需要登录和验证
};

enum XH_SUPER_ROOM_TYPE
{
	XH_SUPER_ROOM_TYPE_GLOBAL_PUBLIC, //无需登录和验证
	XH_SUPER_ROOM_TYPE_LOGIN_PUBLIC, //需要登录，无需验证
	XH_SUPER_ROOM_TYPE_LOGIN_SPECIFY //需要登录和验证
};

enum CHATROOM_LIST_TYPE
{
	CHATROOM_LIST_TYPE_CHATROOM,
	CHATROOM_LIST_TYPE_LIVE,
	CHATROOM_LIST_TYPE_LIVE_PUSH,
	CHATROOM_LIST_TYPE_MEETING,
	CHATROOM_LIST_TYPE_MEETING_PUSH,
	CHATROOM_LIST_TYPE_CLASS,
	CHATROOM_LIST_TYPE_CLASS_PUSH,
	CHATROOM_LIST_TYPE_AUDIO_LIVE,
	CHATROOM_LIST_TYPE_AUDIO_LIVE_PUSH,
	CHATROOM_LIST_TYPE_SUPER_ROOM,
	CHATROOM_LIST_TYPE_SUPER_ROOM_PUSH
};

enum LIVE_MEDIA_TYPE {
	LIVE_MEDIA_TYPE_VIDEO_AND_AUDIO,
	LIVE_MEDIA_TYPE_VIDEO_ONLY,
	LIVE_MEDIA_TYPE_AUDIO_ONLY
};
#endif